services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    restart: always
    env_file: .env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    restart: always
    env_file: .env
    secrets:
      - db_password
      - wp_admin_password
    volumes:
      - wp:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception

  nginx:
    container_name: nginx
    build: requirements/nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/jmafueni/data/mariadb
      o: bind

  wp:
    driver: local
    driver_opts:
      type: none
      device: /home/jmafueni/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt



# name: inception


# services:
#   mariadb:
#     build:
#       context: ./srcs/requirements/mariadb
#       dockerfile: Dockerfile
#     container_name: mariadb
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpassword
#       MYSQL_DATABASE: wordpress
#       MYSQL_USER: wpuser
#       MYSQL_PASSWORD: wppassword
#     volumes:
#       - db_data:/var/lib/mysql
#     networks:
#       - wp-network

#   wordpress:
#     build:
#       context: ./srcs/requirements/wordpress
#       dockerfile: Dockerfile
#     container_name: wordpress
#     depends_on:
#       - mariadb
#     environment:
#       WORDPRESS_DB_HOST: mariadb:3306
#       WORDPRESS_DB_USER: wpuser
#       WORDPRESS_DB_PASSWORD: wppassword
#       WORDPRESS_DB_NAME: wordpress
#     volumes:
#       - wp_data:/var/www/html
#     networks:
#       - wp-network

#   nginx:
#     build:
#       context: ./srcs/requirements/nginx
#       dockerfile: Dockerfile
#     container_name: nginx
#     depends_on:
#       - wordpress
#     ports:
#       - "443:443"
#     volumes:
#       - wp_data:/var/www/html
#       - ./srcs/requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
#     networks:
#       - wp-network

# volumes:
#   db_data:
#   wp_data:

# networks:
#   wp-network:

